### ISSUE TITLE
Creating ruleset for Traits

### ISSUE THREAD

**Issue by Itiweb** [aml-org/amf-custom-validator#120]
I would like creating the ruleset that will contains traits which should be imported from exchange.. Like below

traits:
uuid: !include /exchange_modules/x-uuid-id/1.0.1/x-uuid-id.raml.
Any suggestion on this.

**Comment by nschejtman** [comment]
This is very difficult to achieve. You can check the referenced paths in the produced AMF model. I suggest using this tool to obtain such model https://www.npmjs.com/package/@aml-org/ruleset-development-cli. Once you obtain it you can check the information u have to play around

**Comment by tomsfernandez** [comment]
@Itiweb for the moment we don't support applying custom validations on the "design-view" of an API, we just support applying it on "effective-view". The "effective-view" is with traits and resource types applied.
