### ISSUE TITLE
ruleset-development-cli throwing typscript error

### ISSUE THREAD

**Issue by Jitu-Ranjan** [aml-org/amf-custom-validator#141]
Hi,

I am using the following version of Cli

jituranjan@Jitus-Air amf % ruleset-development-cli --version
@aml-org/ruleset-development-cli/0.4.34 darwin-arm64 node-v20.3.1

But running a new rule command throws a typescript error

jituranjan@Jitus-Air amf % ruleset-development-cli new ~/destin/amf/rules
    TypeError: Cannot set property crypto of #<Object> which has only a getter

**Comment by nschejtman** [comment]
Hi @Jitu-Ranjan this occurs due to the Node version (I believe since Node 19). Currently we officially support Node 16
