### ISSUE TITLE
ruleset-development-cli fails with TypeError

### ISSUE THREAD

**Issue by florintene** [aml-org/amf-custom-validator#144]
### What version of NodeJS are you using ?
```
$ node --version                                                                     
v20.7.0
```

### What version of NPM are you using ?
```
$ npm --version                                                                            
10.1.0
```

### Does this issue reproduce with the latest release?
Yes

### Which version is installed?
```
$ npm list -g                                                                              
├── @aml-org/ruleset-development-cli@0.4.36
```

### What did you do?

1. Installed the package from https://www.npmjs.com/package/@aml-org/ruleset-development-cli
2. Run the command as per the tutorial from here: https://github.com/aml-org/amf-custom-validator/blob/develop/docs/validation_tutorial/validation.md
`ruleset-development-cli new ruleset_tutorial`

### What did you expect to see?
Success

### What did you see instead?
```
ruleset-development-cli test                                                             
    TypeError: Cannot set property crypto of #<Object> which has only a getter
```

There seems to be a problem running the `ruleset-development-cli`. I've tried the 0.4.35 version same result.

Any help much appreciated.

Thank you,
Florin

**Comment by nschejtman** [comment]
Hi @florintene, Node 16 should work

**Comment by florintene** [comment]
hey @nschejtman, 

  Thank you for the quick reply. I can confirm is working with the 16.x.
  It might be worth just to add this info in the readme :) i'm pretty sure there will be others like me.

Thanks a lot again - much appreciated.
